"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

type Profile = { id: string; alias: string; ageBand: string; communicationModes: string[]; supports: { id: string; label: string; accepted: boolean }[] };
export function ProfilesClient() {
  const [profiles, setProfiles] = useState<Profile[]>([]); const [authenticated, setAuthenticated] = useState<boolean | null>(null); const [status, setStatus] = useState("");
  const load = () => fetch("/api/v1/profiles").then((r) => r.json()).then((r) => { setAuthenticated(r.ok); if (r.ok) setProfiles(r.data); });
  useEffect(() => { load(); }, []);
  async function create(form: FormData) { const body = { alias: form.get("alias"), ageBand: form.get("ageBand"), communicationModes: String(form.get("communicationModes") ?? "").split(",").map((x) => x.trim()).filter(Boolean), sensitivities: form.get("sensitivities") || undefined, observableSigns: form.get("observableSigns") || undefined, saveOfflineAllowed: form.get("saveOfflineAllowed") === "on" }; const response = await fetch("/api/v1/profiles", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); setStatus(result.ok ? "Perfil creado." : result.error.message); if (result.ok) load(); }
  if (authenticated === false) return <div className="card"><h2>Tu ayuda inmediata sigue disponible</h2><p className="muted">Inicia sesión únicamente si quieres guardar perfiles, apoyos o planes.</p><Link className="button button-primary" href="/login">Iniciar sesión</Link></div>;
  return <div className="grid"><form className="card" action={create}><h2>Nuevo perfil mínimo</h2><div className="field"><label htmlFor="alias">Alias o iniciales</label><input id="alias" name="alias" required maxLength={50} /></div><div className="field"><label htmlFor="ageBand">Rango de edad</label><select id="ageBand" name="ageBand"><option value="2-4">2 a 4</option><option value="5-8">5 a 8</option><option value="9-12">9 a 12</option><option value="13-17">13 a 17</option></select></div><div className="field"><label htmlFor="communicationModes">Formas de comunicación</label><input id="communicationModes" name="communicationModes" placeholder="Texto, señas, pictogramas" /></div><div className="field"><label htmlFor="sensitivities">Sensibilidades conocidas</label><textarea id="sensitivities" name="sensitivities" /></div><div className="field"><label htmlFor="observableSigns">Señales observables habituales</label><textarea id="observableSigns" name="observableSigns" /></div><label><input type="checkbox" name="saveOfflineAllowed" /> Autorizar plan mínimo en este dispositivo</label><div className="actions"><button className="button button-primary">Guardar perfil</button></div><p role="status">{status}</p></form><div className="card"><h2>Perfiles</h2>{profiles.length === 0 ? <p className="muted">Todavía no hay perfiles guardados.</p> : <div className="resource-list">{profiles.map((p) => <article className="resource" key={p.id}><div><strong>{p.alias}</strong><span>{p.ageBand} años · {p.communicationModes.join(", ") || "Sin forma indicada"}</span></div><Link className="text-link" href={`/profiles/${p.id}`}>Abrir</Link></article>)}</div>}</div></div>;
}
