"use client";
import { useState } from "react";
import { SOAP_DISCLAIMER, buildReport, type ReportPayload } from "@/domain/postcrisis/report";

export function PostcrisisForm() {
  const [type, setType] = useState<"CRISIS_SHEET" | "SOAP_DRAFT">("CRISIS_SHEET"); const [preview, setPreview] = useState<ReturnType<typeof buildReport> | null>(null);
  function prepare(data: FormData) { const payload = Object.fromEntries(data) as unknown as ReportPayload; setPreview(buildReport(type, payload)); }
  return <div className="grid"><form className="card" action={prepare}><div className="field"><label htmlFor="type">Documento</label><select id="type" value={type} onChange={(e) => setType(e.target.value as typeof type)}><option value="CRISIS_SHEET">Hoja de Crisis</option><option value="SOAP_DRAFT">Borrador SOAP</option></select></div><div className="field"><label htmlFor="title">Título</label><input id="title" name="title" defaultValue={type === "SOAP_DRAFT" ? "Borrador SOAP" : "Hoja de Crisis"} /></div><div className="field"><label htmlFor="approximateDate">Fecha y hora aproximada</label><input id="approximateDate" name="approximateDate" /></div><div className="field"><label htmlFor="environment">Entorno</label><input id="environment" name="environment" /></div><div className="field"><label htmlFor="priorContext">Contexto previo</label><textarea id="priorContext" name="priorContext" /></div><div className="field"><label htmlFor="observableBehavior">Conductas observables</label><textarea id="observableBehavior" name="observableBehavior" /></div><div className="field"><label htmlFor="strategies">Estrategias ofrecidas</label><textarea id="strategies" name="strategies" /></div><div className="field"><label htmlFor="describedOutcome">Resultado descrito</label><textarea id="describedOutcome" name="describedOutcome" /></div><div className="field"><label htmlFor="possibleFactors">Factores posibles (hipótesis)</label><textarea id="possibleFactors" name="possibleFactors" /></div><div className="field"><label htmlFor="prevention">Próxima estrategia preventiva</label><textarea id="prevention" name="prevention" /></div><div className="actions"><button className="button button-primary">Preparar vista previa</button></div></form><div className="card"><h2>Vista previa</h2>{!preview ? <p className="muted">Nada se genera ni se guarda hasta que tú lo solicites.</p> : <article><h3>{preview.title}</h3><div className="notice">{type === "SOAP_DRAFT" ? SOAP_DISCLAIMER : preview.disclaimer}</div>{preview.sections.map((s) => <section key={s.heading}><h4>{s.heading}</h4><p>{s.body}</p></section>)}<div className="actions"><button className="button button-secondary" onClick={() => window.print()}>Imprimir o guardar PDF</button></div></article>}</div></div>;
}
