import { z } from "zod";
import { db } from "@/infrastructure/db/client";
import { getCurrentUser } from "@/infrastructure/auth/session";
import { decryptField, encryptField } from "@/infrastructure/crypto/fields";
import { ok, problem, readJson, safeError } from "@/lib/api";

async function owned(id: string, userId: string) { return db.postcrisisReport.findFirst({ where: { id, ownerUserId: userId, deletedAt: null } }); }
export async function GET(_r: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await getCurrentUser(); if (!user) return problem(401, "AUTH_REQUIRED", "Inicia sesión."); const report = await owned((await params).id, user.id); if (!report) return problem(404, "NOT_FOUND", "Reporte no encontrado."); return ok({ id: report.id, type: report.reportType, status: report.status, document: JSON.parse(decryptField(report.contentEncrypted)), createdAt: report.createdAt }); } catch (error) { return safeError(error); } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await getCurrentUser(); if (!user) return problem(401, "AUTH_REQUIRED", "Inicia sesión."); const { id } = await params; if (!await owned(id, user.id)) return problem(404, "NOT_FOUND", "Reporte no encontrado."); const body = await readJson(request, z.object({ document: z.object({ title: z.string().max(160), disclaimer: z.string().max(500), sections: z.array(z.object({ heading: z.string().max(120), body: z.string().max(5000) })).max(20) }), status: z.enum(["DRAFT", "FINAL"]).optional() })); await db.postcrisisReport.update({ where: { id }, data: { contentEncrypted: encryptField(JSON.stringify(body.document)), status: body.status } }); return ok({ updated: true }); } catch (error) { return safeError(error); } }
export async function DELETE(_r: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await getCurrentUser(); if (!user) return problem(401, "AUTH_REQUIRED", "Inicia sesión."); const { id } = await params; if (!await owned(id, user.id)) return problem(404, "NOT_FOUND", "Reporte no encontrado."); await db.postcrisisReport.update({ where: { id }, data: { deletedAt: new Date(), status: "DELETED", contentEncrypted: encryptField("{}") } }); return ok({ deleted: true }); } catch (error) { return safeError(error); } }
