"use client";
import { useEffect, useState } from "react";

export function SettingsClient() {
  const [theme, setTheme] = useState("light"); const [contrast, setContrast] = useState(false); const [motion, setMotion] = useState(false); const [status, setStatus] = useState("");
  useEffect(() => { const frame = requestAnimationFrame(() => { const t = localStorage.getItem("nexo-theme") ?? "light"; const c = localStorage.getItem("nexo-contrast") === "high"; const m = localStorage.getItem("nexo-motion") === "reduced"; setTheme(t); setContrast(c); setMotion(m); apply(t, c, m); }); return () => cancelAnimationFrame(frame); }, []);
  function apply(t: string, c: boolean, m: boolean) { document.documentElement.dataset.theme = t; document.documentElement.dataset.contrast = c ? "high" : "normal"; document.documentElement.style.scrollBehavior = m ? "auto" : "smooth"; localStorage.setItem("nexo-theme", t); localStorage.setItem("nexo-contrast", c ? "high" : "normal"); localStorage.setItem("nexo-motion", m ? "reduced" : "normal"); }
  async function privacy(form: FormData, action: "export" | "delete") { setStatus("Procesando…"); const response = await fetch(action === "export" ? "/api/v1/privacy/export" : "/api/v1/account", { method: action === "export" ? "POST" : "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password: form.get("password"), confirm: action === "delete" ? "ELIMINAR" : undefined }) }); if (action === "export" && response.ok) { const blob = await response.blob(); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "nexo-datos.json"; a.click(); URL.revokeObjectURL(url); setStatus("Exportación descargada."); } else { const result = await response.json(); setStatus(result.ok ? "Datos eliminados." : result.error.message); } }
  return <div className="grid"><section className="card"><h2>Lectura y apariencia</h2><div className="field"><label htmlFor="theme">Tema</label><select id="theme" value={theme} onChange={(e) => { setTheme(e.target.value); apply(e.target.value, contrast, motion); }}><option value="light">Claro</option><option value="dark">Oscuro</option></select></div><p><label><input type="checkbox" checked={contrast} onChange={(e) => { setContrast(e.target.checked); apply(theme, e.target.checked, motion); }} /> Alto contraste</label></p><p><label><input type="checkbox" checked={motion} onChange={(e) => { setMotion(e.target.checked); apply(theme, contrast, e.target.checked); }} /> Reducir movimiento</label></p><p className="muted">La velocidad de la voz y el modo solo texto también pueden cambiarse durante la crisis.</p></section><section className="card"><h2>Privacidad y datos</h2><p className="muted">Exportar o eliminar requiere volver a escribir tu contraseña. La crisis invitada no necesita cuenta.</p><form action={(f) => privacy(f, "export")}><div className="field"><label htmlFor="password-export">Contraseña</label><input id="password-export" name="password" type="password" required /></div><div className="actions"><button className="button button-secondary">Exportar mis datos</button></div></form><form action={(f) => privacy(f, "delete")}><div className="field"><label htmlFor="password-delete">Contraseña para eliminar</label><input id="password-delete" name="password" type="password" required /></div><div className="actions"><button className="button button-danger">Eliminar cuenta y datos</button></div></form><p role="status">{status}</p></section></div>;
}
